[build]
  publish = "/"  # Cambia con il percorso corretto
  command = "npm run build"  # Assicurati che questo comando funzioni correttamente

[dev]
  command = "npm start"  # Comando per avviare il server in locale, se applicabile
